Junta\Bundle\SessionBundle\Entity\Session:
    type: entity
    table: session
    id:
        id:
            type: string
            length: 255
    fields:
        data:
            type: blob
        lifetime:
            type: bigint
            options:
                unsigned: true
        timestamp:
            column: updated
            type: integer
            options:
                unsigned: true
